@startuml
title B-1: Authentication Block

<style>
activityDiagram {
  diamond {
    BackgroundColor #ccf
  }
}
</style>

skinparam activity {
  BackgroundColor<<Error>> #e85e58
  BackgroundColor<<ApiCall>> #62e7b2
  BackgroundColor<<Continue>> #e7eba3
  BackgroundColor<<Question>> #e7eba3
}

start
-[#black]-> Call starts;
:AT-1: Welcome;
repeat :AT-2: Start Login;
    if (AT-3: Repeated loop 3 times?) then (Yes)
        <<Error>>:AT-4: Error message;
        -[#black]-> End Call;
        stop
    else (No)
        partition "AT-5: Login Process" {
            :AT-6: Register Membership Id;
            :AT-7: Register PIN;
            <<ApiCall>>:AT-8: Call Auth API;
        }
    endif
repeat while (AT-9: Auth success?) is (No) not (Yes)

:AT-10: Auth success;
<<Continue>>:AT-11: Continue to <b>B-2</b>;

@enduml